# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/deepcopy-gen",
]

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "sigs.k8s.io/cluster-api"
    unused-packages = false

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  revision = "5b128c0f9ab134087d1331be8176099201055a36"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"
